# modules/tymp/constants.py

RIGHT = "right"
LEFT = "left"
SIDES = [RIGHT, LEFT]

STATUS_OK = "ok"
STATUS_PARTIAL = "partial"
STATUS_ERROR = "error"

PRESSURE_SOURCE_OCR_OK = "ocr_ok"
PRESSURE_SOURCE_CV_FALLBACK = "cv_fallback"
PRESSURE_SOURCE_CV_REJECTED_RANGE = "cv_rejected_range"
PRESSURE_SOURCE_NO_RESULT = "no_result"

MIN_ECV_ML = 0.0
MAX_ECV_ML = 5.0

MIN_COMPLIANCE_ML = 0.0
MAX_COMPLIANCE_ML = 5.0

MIN_PRESSURE_DAPA = -600.0
MAX_PRESSURE_DAPA = 300.0

MIN_GRADIENT_DAPA = 0.0
MAX_GRADIENT_DAPA = 300.0

DEFAULT_SCHEMA_VERSION = "tymp_v1"
DEFAULT_MODULE_NAME = "tymp"